<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
دایی موند
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    به اولین تمرین از فصل‌های مدل‌سازی کالج خوش‌آمدید 😊🎉
    <br>
    هدف ما در این مسئله این است که قیمت الماس‌ها را بر اساس تعدادی از ویژگی‌های آن‌ها پیش‌بینی کنیم.
    برای حل این مسئله به سراغ الگوریتم رگرسیون خطی خواهیم رفت.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
مجموعه‌داده‌ آموزشی‌ای که در اختیار داریم شامل ۱۰ ستون است که در جدول زیر، توضیحات هر کدام از ستون‌ها آورده شده است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>carat</code>|وزن الماس به معیار قیراط|
|<code>cut</code>|کیفیت تراش‌خوردگی الماس|
|<code>color</code>|رنگ الماس از J(بدترین) تا D (بهترین)|
|<code>clarity</code>|معیار شفافیت الماس (از چپ به راست از بدترین به بهترین: I1, SI2, SI1, VS2, VS1, VVS2, VVS1, IF)
|<code>x</code>|طول الماس به میلی‌متر|
|<code>y</code>|عرض الماس به میلی‌متر|
|<code>z</code>|عمق الماس به میلی‌متر|
|<code>depth</code>|عمق درصدی که برابر است با z / mean(x,y)|
|<code>table</code>|عرض عریض‌ترین نقطه بالایی الماس|
|<code>price</code>|قیمت الماس|

</font>
</div>
</center>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>diamonds_train.csv</code> و نمونه‌های آزمون که باید قیمت آن‌ها را پیش‌بینی کنید در فایل <code>diamonds_test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از مجموعه‌ی آموزشی را به عنوان مجموعه‌ی اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/ML/Quera_exercise/دایی موند/diamonds_train.csv')
train.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


In [ ]:
test = pd.read_csv('/content/drive/MyDrive/ML/Quera_exercise/دایی موند/diamonds_test.csv')
test.head()

,carat,cut,color,clarity,depth,table,x,y,z
0,0.73,Ideal,G,VVS2,61.9,55.0,5.83,5.77,3.59
1,0.61,Premium,F,VVS2,59.7,58.0,5.56,5.53,3.31
2,1.55,Premium,I,VS1,58.2,60.0,7.69,7.59,4.45
3,0.46,Good,F,IF,56.2,61.0,5.16,5.24,2.92
4,1.10,Very Good,F,VS2,60.6,58.0,6.67,6.77,4.07


In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    50000 non-null  float64
 1   cut      50000 non-null  object 
 2   color    50000 non-null  object 
 3   clarity  50000 non-null  object 
 4   depth    50000 non-null  float64
 5   table    50000 non-null  float64
 6   price    50000 non-null  int64  
 7   x        50000 non-null  float64
 8   y        50000 non-null  float64
 9   z        50000 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 3.8+ MB


In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3940 entries, 0 to 3939
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   carat    3940 non-null   float64
 1   cut      3940 non-null   object 
 2   color    3940 non-null   object 
 3   clarity  3940 non-null   object 
 4   depth    3940 non-null   float64
 5   table    3940 non-null   float64
 6   x        3940 non-null   float64
 7   y        3940 non-null   float64
 8   z        3940 non-null   float64
dtypes: float64(6), object(3)
memory usage: 277.2+ KB


In [ ]:
train.isnull().sum()

,0
carat,0
cut,0
color,0
clarity,0
depth,0
table,0
price,0
x,0
y,0
z,0


In [ ]:
test.isnull().sum()

,0
carat,0
cut,0
color,0
clarity,0
depth,0
table,0
x,0
y,0
z,0


In [ ]:
train.describe()

,carat,depth,table,price,x,y,z
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,0.799444,61.753006,57.457830,3944.805440,5.734403,5.737956,3.541056
std,0.475173,1.431088,2.232092,3997.938105,1.123077,1.145579,0.707065
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,951.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2410.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5351.000000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000


In [ ]:
test.describe()

,carat,depth,table,x,y,z
count,3940.000000,3940.000000,3940.000000,3940.000000,3940.000000,3940.000000
mean,0.778853,61.703706,57.448985,5.689962,5.690992,3.509264
std,0.458643,1.451353,2.264983,1.104228,1.096692,0.687537
min,0.200000,44.000000,50.000000,0.000000,0.000000,0.000000
25%,0.390000,61.000000,56.000000,4.700000,4.700000,2.890000
50%,0.700000,61.800000,57.000000,5.660000,5.660000,3.480000
75%,1.030000,62.500000,59.000000,6.520000,6.510000,4.020000
max,2.770000,68.700000,70.000000,9.110000,9.070000,6.160000


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [ ]:
categorical_columns = train.select_dtypes(include=['object']).columns.tolist()
categorical_columns


['cut', 'color', 'clarity']

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

categorical_columns = ['cut', 'clarity']

for col in categorical_columns:
  encoder = OrdinalEncoder()
  train[col] = encoder.fit_transform(train[[col]])
  test[col] = encoder.transform(test[[col]])

train

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,2.0,E,3.0,61.5,55.0,326,3.95,3.98,2.43
1,0.21,3.0,E,2.0,59.8,61.0,326,3.89,3.84,2.31
2,0.23,1.0,E,4.0,56.9,65.0,327,4.05,4.07,2.31
3,0.29,3.0,I,5.0,62.4,58.0,334,4.20,4.23,2.63
4,0.31,1.0,J,3.0,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
49995,0.72,2.0,D,2.0,60.8,57.0,2757,5.75,5.76,3.50
49996,0.72,1.0,D,2.0,63.1,55.0,2757,5.69,5.75,3.61
49997,0.70,4.0,D,2.0,62.8,60.0,2757,5.66,5.68,3.56
49998,0.86,3.0,H,3.0,61.0,58.0,2757,6.15,6.12,3.74


In [ ]:
test

,carat,cut,color,clarity,depth,table,x,y,z
0,0.73,2.0,G,7.0,61.9,55.0,5.83,5.77,3.59
1,0.61,3.0,F,7.0,59.7,58.0,5.56,5.53,3.31
2,1.55,3.0,I,4.0,58.2,60.0,7.69,7.59,4.45
3,0.46,1.0,F,1.0,56.2,61.0,5.16,5.24,2.92
4,1.10,4.0,F,5.0,60.6,58.0,6.67,6.77,4.07
...,...,...,...,...,...,...,...,...,...
3935,1.58,3.0,I,4.0,61.1,59.0,7.52,7.44,4.57
3936,1.00,4.0,F,2.0,63.1,59.0,6.29,6.22,3.95
3937,1.13,3.0,H,4.0,58.9,58.0,6.81,6.78,4.00
3938,1.51,2.0,E,5.0,62.8,56.0,7.31,7.24,4.57


In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

# Fit and transform the train set
X_train_encoded = encoder.fit_transform(train[['color']])

# Transform the test set
X_test_encoded = encoder.transform(test[['color']])

In [ ]:
X_train_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 50000 stored elements and shape (50000, 7)>

In [ ]:
X_test_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3940 stored elements and shape (3940, 7)>

In [ ]:
X_train_encoded = pd.DataFrame(X_train_encoded.toarray())

In [ ]:
X_train_encoded

,0,1,2,3,4,5,6
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...
49995,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49996,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49997,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49998,0.0,0.0,0.0,0.0,1.0,0.0,0.0


In [ ]:
train

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,2.0,E,3.0,61.5,55.0,326,3.95,3.98,2.43
1,0.21,3.0,E,2.0,59.8,61.0,326,3.89,3.84,2.31
2,0.23,1.0,E,4.0,56.9,65.0,327,4.05,4.07,2.31
3,0.29,3.0,I,5.0,62.4,58.0,334,4.20,4.23,2.63
4,0.31,1.0,J,3.0,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
49995,0.72,2.0,D,2.0,60.8,57.0,2757,5.75,5.76,3.50
49996,0.72,1.0,D,2.0,63.1,55.0,2757,5.69,5.75,3.61
49997,0.70,4.0,D,2.0,62.8,60.0,2757,5.66,5.68,3.56
49998,0.86,3.0,H,3.0,61.0,58.0,2757,6.15,6.12,3.74


In [ ]:
test

,carat,cut,color,clarity,depth,table,x,y,z
0,0.73,2.0,G,7.0,61.9,55.0,5.83,5.77,3.59
1,0.61,3.0,F,7.0,59.7,58.0,5.56,5.53,3.31
2,1.55,3.0,I,4.0,58.2,60.0,7.69,7.59,4.45
3,0.46,1.0,F,1.0,56.2,61.0,5.16,5.24,2.92
4,1.10,4.0,F,5.0,60.6,58.0,6.67,6.77,4.07
...,...,...,...,...,...,...,...,...,...
3935,1.58,3.0,I,4.0,61.1,59.0,7.52,7.44,4.57
3936,1.00,4.0,F,2.0,63.1,59.0,6.29,6.22,3.95
3937,1.13,3.0,H,4.0,58.9,58.0,6.81,6.78,4.00
3938,1.51,2.0,E,5.0,62.8,56.0,7.31,7.24,4.57


In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the train set
X_train_encoded = encoder.fit_transform(train[['color']])

# Transform the test set
X_test_encoded = encoder.transform(test[['color']])

In [ ]:
X_train_encoded

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_test_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_train_encoded = pd.DataFrame(X_train_encoded)
X_train_encoded

,0,1,2,3,4,5,6
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...
49995,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49996,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49997,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49998,0.0,0.0,0.0,0.0,1.0,0.0,0.0


In [ ]:
X_test_encoded = pd.DataFrame(X_test_encoded)
X_test_encoded

,0,1,2,3,4,5,6
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
3935,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3936,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3937,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3938,0.0,1.0,0.0,0.0,0.0,0.0,0.0


In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit and transform the train set
X_train_encoded = encoder.fit_transform(train[['color']])

# Transform the test set
X_test_encoded = encoder.transform(test[['color']])

In [ ]:
X_train_encoded

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_test_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_train_encoded = pd.DataFrame(X_train_encoded)
X_train_encoded

,0,1,2,3,4,5,6
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...
49995,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49996,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49997,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49998,0.0,0.0,0.0,0.0,1.0,0.0,0.0


In [ ]:
X_test_encoded = pd.DataFrame(X_test_encoded)
X_test_encoded

,0,1,2,3,4,5,6
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
3935,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3936,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3937,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3938,0.0,1.0,0.0,0.0,0.0,0.0,0.0


In [ ]:
train = pd.concat([train, X_train_encoded], axis=1)

del train['color']

train

,carat,cut,clarity,depth,table,price,x,y,z,0,1,2,3,4,5,6
0,0.23,2.0,3.0,61.5,55.0,326,3.95,3.98,2.43,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.21,3.0,2.0,59.8,61.0,326,3.89,3.84,2.31,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.23,1.0,4.0,56.9,65.0,327,4.05,4.07,2.31,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.29,3.0,5.0,62.4,58.0,334,4.20,4.23,2.63,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.31,1.0,3.0,63.3,58.0,335,4.34,4.35,2.75,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0.72,2.0,2.0,60.8,57.0,2757,5.75,5.76,3.50,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49996,0.72,1.0,2.0,63.1,55.0,2757,5.69,5.75,3.61,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49997,0.70,4.0,2.0,62.8,60.0,2757,5.66,5.68,3.56,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49998,0.86,3.0,3.0,61.0,58.0,2757,6.15,6.12,3.74,0.0,0.0,0.0,0.0,1.0,0.0,0.0


In [ ]:
test = pd.concat([test, X_test_encoded], axis=1)

del test['color']

test

,carat,cut,clarity,depth,table,x,y,z,0,1,2,3,4,5,6
0,0.73,2.0,7.0,61.9,55.0,5.83,5.77,3.59,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.61,3.0,7.0,59.7,58.0,5.56,5.53,3.31,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1.55,3.0,4.0,58.2,60.0,7.69,7.59,4.45,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.46,1.0,1.0,56.2,61.0,5.16,5.24,2.92,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1.10,4.0,5.0,60.6,58.0,6.67,6.77,4.07,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,1.58,3.0,4.0,61.1,59.0,7.52,7.44,4.57,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3936,1.00,4.0,2.0,63.1,59.0,6.29,6.22,3.95,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3937,1.13,3.0,4.0,58.9,58.0,6.81,6.78,4.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3938,1.51,2.0,5.0,62.8,56.0,7.31,7.24,4.57,0.0,1.0,0.0,0.0,0.0,0.0,0.0


In [ ]:
print(train.columns)


Index([  'carat',     'cut', 'clarity',   'depth',   'table',   'price',
             'x',       'y',       'z',         0,         1,         2,
               3,         4,         5,         6],
      dtype='object')


In [ ]:
train.columns = train.columns.astype(str)
test.columns = test.columns.astype(str)


from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = train.drop(['price'], axis=1)

X_train = sc.fit_transform(X_train)
X_test = sc.transform(test)

X_train

array([[-1.1984046 , -0.53821479, -0.48546689, ..., -0.42701354,
        -0.33547736, -0.23449065],
       [-1.24049496,  0.43445083, -1.06579405, ..., -0.42701354,
        -0.33547736, -0.23449065],
       [-1.1984046 , -1.51088041,  0.09486028, ..., -0.42701354,
        -0.33547736, -0.23449065],
       ...,
       [-0.20928124,  1.40711645, -1.06579405, ..., -0.42701354,
        -0.33547736, -0.23449065],
       [ 0.1274416 ,  0.43445083, -0.48546689, ...,  2.34184613,
        -0.33547736, -0.23449065],
       [-0.10405536, -0.53821479, -0.48546689, ..., -0.42701354,
        -0.33547736, -0.23449065]])

In [ ]:
X_test

array([[-0.14614571, -0.53821479,  1.83584177, ..., -0.42701354,
        -0.33547736, -0.23449065],
       [-0.39868784,  0.43445083,  1.83584177, ..., -0.42701354,
        -0.33547736, -0.23449065],
       [ 1.57955887,  0.43445083,  0.09486028, ..., -0.42701354,
         2.98082709, -0.23449065],
       ...,
       [ 0.6956614 ,  0.43445083,  0.09486028, ...,  2.34184613,
        -0.33547736, -0.23449065],
       [ 1.49537815, -0.53821479,  0.67518744, ..., -0.42701354,
        -0.33547736, -0.23449065],
       [ 1.57955887, -0.53821479, -0.48546689, ..., -0.42701354,
        -0.33547736, -0.23449065]])

In [ ]:
X_train = pd.DataFrame(X_train, columns=train.columns.drop('price'))

train = pd.concat([X_train, train['price']], axis=1)

train

,carat,cut,clarity,depth,table,x,y,z,0,1,2,3,4,5,6,price
0,-1.198405,-0.538215,-0.485467,-0.176795,-1.101144,-1.588868,-1.534572,-1.571380,-0.377065,2.122163,-0.464199,-0.514088,-0.427014,-0.335477,-0.234491,326
1,-1.240495,0.434451,-1.065794,-1.364714,1.586944,-1.642293,-1.656782,-1.741097,-0.377065,2.122163,-0.464199,-0.514088,-0.427014,-0.335477,-0.234491,326
2,-1.198405,-1.510880,0.094860,-3.391165,3.379003,-1.499826,-1.456009,-1.741097,-0.377065,2.122163,-0.464199,-0.514088,-0.427014,-0.335477,-0.234491,327
3,-1.072134,0.434451,0.675187,0.452104,0.242900,-1.366263,-1.316340,-1.288517,-0.377065,-0.471217,-0.464199,-0.514088,-0.427014,2.980827,-0.234491,334
4,-1.030043,-1.510880,-0.485467,1.081003,0.242900,-1.241604,-1.211588,-1.118800,-0.377065,-0.471217,-0.464199,-0.514088,-0.427014,-0.335477,4.264562,335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-0.167191,-0.538215,-1.065794,-0.665938,-0.205115,0.013888,0.019243,-0.058066,2.652059,-0.471217,-0.464199,-0.514088,-0.427014,-0.335477,-0.234491,2757
49996,-0.167191,-1.510880,-1.065794,0.941247,-1.101144,-0.039538,0.010513,0.097508,2.652059,-0.471217,-0.464199,-0.514088,-0.427014,-0.335477,-0.234491,2757
49997,-0.209281,1.407116,-1.065794,0.731615,1.138930,-0.066250,-0.050592,0.026793,2.652059,-0.471217,-0.464199,-0.514088,-0.427014,-0.335477,-0.234491,2757
49998,0.127442,0.434451,-0.485467,-0.526183,0.242900,0.370055,0.333497,0.281369,-0.377065,-0.471217,-0.464199,-0.514088,2.341846,-0.335477,-0.234491,2757


In [ ]:
test = pd.DataFrame(X_test, columns=test.columns)

test

,carat,cut,clarity,depth,table,x,y,z,0,1,2,3,4,5,6
0,-0.146146,-0.538215,1.835842,0.102716,-1.101144,0.085121,0.027972,0.069222,-0.377065,-0.471217,-0.464199,1.945192,-0.427014,-0.335477,-0.234491
1,-0.398688,0.434451,1.835842,-1.434592,0.242900,-0.155292,-0.181531,-0.326785,-0.377065,-0.471217,2.154250,-0.514088,-0.427014,-0.335477,-0.234491
2,1.579559,0.434451,0.094860,-2.482756,1.138930,1.741301,1.616704,1.285530,-0.377065,-0.471217,-0.464199,-0.514088,-0.427014,2.980827,-0.234491
3,-0.714366,-1.510880,-1.646121,-3.880309,1.586944,-0.511460,-0.434681,-0.878367,-0.377065,-0.471217,2.154250,-0.514088,-0.427014,-0.335477,-0.234491
4,0.632526,1.407116,0.675187,-0.805693,0.242900,0.833073,0.900901,0.748092,-0.377065,-0.471217,2.154250,-0.514088,-0.427014,-0.335477,-0.234491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3935,1.642694,0.434451,0.094860,-0.456305,0.690915,1.589930,1.485764,1.455248,-0.377065,-0.471217,-0.464199,-0.514088,-0.427014,2.980827,-0.234491
3936,0.422074,1.407116,-1.065794,0.941247,0.690915,0.494714,0.420790,0.578374,-0.377065,-0.471217,2.154250,-0.514088,-0.427014,-0.335477,-0.234491
3937,0.695661,0.434451,0.094860,-1.993613,0.242900,0.957732,0.909631,0.649090,-0.377065,-0.471217,-0.464199,-0.514088,2.341846,-0.335477,-0.234491
3938,1.495378,-0.538215,0.675187,0.731615,-0.653129,1.402942,1.311178,1.455248,-0.377065,2.122163,-0.464199,-0.514088,-0.427014,-0.335477,-0.234491


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    حال که داده‌ها را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
    الگوریتم <code>LinearRegression</code> نیز در کتابخانه‌ی <code>scikit-learn</code> به‌خوبی پیاده‌سازی شده و می‌توانیم از آن جهت اجرای الگوریتم <i>رگرسیون خطی</i> بر روی داده‌های خود کمک بگیریم.
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در سلول پایین با استفاده از کتابخانه <code>scikit-learn</code> مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
    <br>
    <b>حتما باید از مدل رگرسیون خطی یعنی <code>LinearRegression</code> استفاده کنید.</b>
</font>
</p>

In [ ]:
from sklearn.linear_model import LinearRegression

X = train.drop(['price'], axis = 1)

y = train['price']

model = LinearRegression().fit(X, y)

y_pred = model.predict(X)
print(f"predicted response:\n{y_pred}")


predicted response:
[ -14.02754671 -646.84849641  -95.49355819 ... 2584.80902943 3655.70206079
 3615.95751999]


<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>r2_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

In [ ]:
from sklearn.metrics import r2_score

score = r2_score(y, y_pred)
score * 100

88.94277498286445

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>80</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدل‌سازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول زیر آماده کنید.
</font>
</p>

<center>
<div dir=rtl style="line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>price</code>|قیمت پیش‌بینی‌شده برای الماس|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
توجه داشته باشید که:
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium; margin-right:48px">
<font face="vazir" size=3>
    ۱. نام دیتافریم پاسخ شما حتماً باید <code>submission</code> باشد، در غیر این‌صورت سامانه‌ی داوری نمی‌تواند تلاش شما را ارزیابی کند.
    <br>
    ۲. این دیتافریم تنها شامل یک ستون با نام <code>price</code> بوده و شامل ۳۹۴۰ ردیف است.
    <br>
    ۳. ترتیب ردیف‌های دیتافریم باید دقیقاً مطابق با نمونه‌های آزمون باشد. یعنی به‌عنوان مثال اولین ردیف شما باید پیش‌بینی مدل‌تان برای نمونه‌ی آزمون اول باشد.
</font>
</p>

In [ ]:
y_test = model.predict(test)
print(f"predicted response:\n{y_test}")


predicted response:
[ 4051.59172664  3447.43361349  9713.94608231 ...  6455.41128657
 10640.34031189 10130.65789572]


In [ ]:
# predict test samples
submission = pd.DataFrame(y_test, columns=['price'])

submission

,price
0,4051.591727
1,3447.433613
2,9713.946082
3,644.916929
4,6920.220419
...,...
3935,9871.984441
3936,4892.965851
3937,6455.411287
3938,10640.340312


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
joblib.dump(model, 'model')
file_names = ['diamond.ipynb', 'submission.csv', 'model']
compress(file_names)

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>راهنمایی</b>
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ۱. ستون‌های دسته‌ای (<i>categorical</i>) دیتافریم را می‌توانید <code>labelEncode</code> کنید.
    <br>
    ۲. فراموش نکنید که مراحل پیش‌پردازش خود را بر روی نمونه‌های آزمون نیز اعمال کنید.
</font>
</p>